#!/usr/bin/env python3
"""Generate pipeline_figure.tex: the study pipeline as one mechanism drawing.

Revision 2026-09-06 (second pass after co-author review). The first reduction had
turned the figure into five text boxes. This version draws the one thing the reader
must hold in mind for the whole results section: three conditions differ only in who
plays the client, all three pass through the same measurement, and the outcome is two
distances to the same reference whose difference is the proximity gap Delta. The three
lanes keep their order from left to right, and in the last panel the lane height doubles
as the distance axis. No numbers: the hero figure and the noise-band figure carry them.
The three unit types, the robustness checks and the model list live in the text.

Older versions: make_pipeline_tikz.py.bak_detailed (infographic with mini-plots),
make_pipeline_tikz.py.bak_textonly (five text boxes).

Usage:
    python analysis/semantic/oncoco/make_pipeline_tikz.py            # writes + compiles
    python analysis/semantic/oncoco/make_pipeline_tikz.py --no-compile
"""
from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "results" / "figures" / "oncoco" / "tikz" / "pipeline_figure.tex"

W, H = 16.90, 5.45
Y_REAL, Y_RP, Y_LLM = 4.10, 2.80, 1.50       # lane heights (top to bottom)
Y_HEAD = H - 0.32                             # panel headers

# lane: (key, colour, label, who plays the client)
LANES = [
    ("real", "cReal", "HH real", "real client, archived chats"),
    ("rp", "cRP", "HH roleplay", "trainee plays the client"),
    ("llm", "cLLM", "H--LLM roleplay", "LLM plays the client"),
]
LANE_Y = {"real": Y_REAL, "rp": Y_RP, "llm": Y_LLM}

# schematic category profiles (relative bar heights, no data behind them)
PROFILE = {
    "real": [0.95, 0.70, 0.55, 0.42, 0.30, 0.22, 0.15, 0.10],
    "rp":   [0.85, 0.75, 0.48, 0.45, 0.26, 0.28, 0.12, 0.12],
    "llm":  [0.50, 0.28, 0.95, 0.18, 0.62, 0.14, 0.42, 0.30],
}

# panel x-ranges
P1 = (0.00, 4.90)      # conditions
P2 = (5.35, 8.80)      # shared measurement box
P3 = (9.30, 11.75)     # category profiles
P4 = (12.25, W)        # distance to real

HEADER = r"""%% Study pipeline for the LAK/JLA submission -- standalone TikZ.
%% GENERATED by analysis/semantic/oncoco/make_pipeline_tikz.py -- do not edit by hand.
\documentclass[border=1pt,10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage[scaled=0.92]{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{sansmath}
\sansmath
\usepackage{tikz}
\usetikzlibrary{arrows.meta,calc,decorations.pathreplacing}

\definecolor{cReal}{HTML}{2C6E63}
\definecolor{cRP}{HTML}{4A6E9B}
\definecolor{cLLM}{HTML}{C0503C}
\definecolor{cAcc}{HTML}{7A5EA6}
\definecolor{cInk}{HTML}{1F2328}
\definecolor{cMeas}{HTML}{3F4A57}
\definecolor{cMute}{HTML}{70757D}
\definecolor{cRule}{HTML}{CFD4DA}
\definecolor{cPanel}{HTML}{FBFBFC}
\definecolor{cBand}{HTML}{E4E8EC}
\definecolor{cChip}{HTML}{E9ECEF}

\begin{document}
\begin{tikzpicture}[x=1cm,y=1cm,
  lane/.style={-{Stealth[length=4pt,width=4pt]}, line width=1.0pt},
  hdr/.style={anchor=west, font=\small\bfseries, text=cInk, inner sep=0pt},
  num/.style={circle, fill=cInk, text=white, inner sep=0pt, minimum size=4.2mm, font=\bfseries\footnotesize},
  muted/.style={font=\footnotesize, text=cMute, inner sep=0pt},
]
\path (0,0) rectangle (%(W).2f,%(H).2f);
"""

FOOTER = r"""\end{tikzpicture}
\end{document}
"""


def header(num: int, x: float, title: str) -> str:
    return (f"\\node[num] at ({x + 0.21:.2f},{Y_HEAD:.2f}) {{{num}}};\n"
            f"\\node[hdr] at ({x + 0.50:.2f},{Y_HEAD:.2f}) {{{title}}};\n")


def panel_conditions() -> str:
    x0, x1 = P1
    t = "% ---- panel 1: conditions\n" + header(1, x0, "Three chat conditions")
    chip_w, chip_h, chip_gap = 0.30, 0.20, 0.07
    n_chips = 4
    chips_x0 = x1 - n_chips * chip_w - (n_chips - 1) * chip_gap
    for key, col, label, who in LANES:
        y = LANE_Y[key]
        t += (f"\\node[anchor=west, font=\\small\\bfseries, text={col}, inner sep=0pt] "
              f"at ({x0:.2f},{y + 0.14:.2f}) {{{label}}};\n")
        t += f"\\node[anchor=west, muted] at ({x0:.2f},{y - 0.16:.2f}) {{{who}}};\n"
        # alternating turns: counselor (grey) / client (condition colour)
        for k in range(n_chips):
            cx = chips_x0 + k * (chip_w + chip_gap)
            fill = col if k % 2 == 1 else "cChip"
            t += (f"\\fill[{fill}, rounded corners=1.2pt] ({cx:.2f},{y - chip_h / 2:.2f}) "
                  f"rectangle ({cx + chip_w:.2f},{y + chip_h / 2:.2f});\n")
    # legend for the chips
    lx = chips_x0 - 2.00
    ly = Y_LLM - 0.62
    t += (f"\\fill[cChip, rounded corners=1.2pt] ({lx:.2f},{ly - 0.08:.2f}) rectangle ({lx + 0.22:.2f},{ly + 0.08:.2f});\n"
          f"\\node[anchor=west, muted] at ({lx + 0.28:.2f},{ly:.2f}) {{counselor turn}};\n"
          f"\\fill[cMeas, rounded corners=1.2pt] ({lx + 2.00:.2f},{ly - 0.08:.2f}) rectangle ({lx + 2.22:.2f},{ly + 0.08:.2f});\n"
          f"\\node[anchor=west, muted] at ({lx + 2.28:.2f},{ly:.2f}) {{client turn}};\n")
    return t


def panel_measurement() -> str:
    x0, x1 = P2
    box_top, box_bot = Y_REAL + 0.55, Y_LLM - 0.72
    t = "% ---- panel 2: one measurement for all three\n" + header(2, x0, "Same measurement")
    t += (f"\\draw[rounded corners=3pt, draw=cRule, fill=cPanel, line width=0.6pt] "
          f"({x0:.2f},{box_bot:.2f}) rectangle ({x1:.2f},{box_top:.2f});\n")
    # lanes in and out
    for key, col, _, _ in LANES:
        y = LANE_Y[key]
        t += f"\\draw[lane, {col}] ({P1[1] + 0.08:.2f},{y:.2f}) -- ({x0 - 0.04:.2f},{y:.2f});\n"
        t += f"\\draw[lane, {col}] ({x1 + 0.04:.2f},{y:.2f}) -- ({P3[0] - 0.06:.2f},{y:.2f});\n"
    cx = (x0 + x1) / 2
    bw = x1 - x0 - 0.60
    # two stacked steps inside the box
    steps = [
        (Y_REAL + 0.02, "split into spans", "SaT-6l + LoRA segmenter"),
        (Y_RP - 0.22, "OnCoCo classifier", "66 role-specific categories"),
    ]
    for yc, head, sub in steps:
        t += (f"\\node[anchor=north, font=\\small\\bfseries, text=cInk, inner sep=0pt, text width={bw:.2f}cm, align=center] "
              f"at ({cx:.2f},{yc:.2f}) {{{head}}};\n")
        t += (f"\\node[anchor=north, muted, text width={bw:.2f}cm, align=center] "
              f"at ({cx:.2f},{yc - 0.30:.2f}) {{{sub}}};\n")
    t += (f"\\draw[-{{Stealth[length=3.5pt,width=3.5pt]}}, cMute, line width=0.8pt] "
          f"({cx:.2f},{Y_REAL - 0.66:.2f}) -- ({cx:.2f},{Y_RP - 0.16:.2f});\n")
    t += (f"\\node[anchor=north, muted, text width={bw:.2f}cm, align=center] "
          f"at ({cx:.2f},{box_bot + 0.34:.2f}) {{identical for all three conditions}};\n")
    return t


def panel_profiles() -> str:
    x0, x1 = P3
    t = "% ---- panel 3: category profiles\n" + header(3, x0, "Category profile")
    n = len(PROFILE["real"])
    bar_w, bar_gap, bar_h = 0.20, 0.06, 0.78
    total = n * bar_w + (n - 1) * bar_gap
    bx0 = x0 + (x1 - x0 - total) / 2
    for key, col, _, _ in LANES:
        y = LANE_Y[key]
        base = y - bar_h / 2
        t += f"\\draw[cRule, line width=0.4pt] ({bx0 - 0.06:.2f},{base:.2f}) -- ({bx0 + total + 0.06:.2f},{base:.2f});\n"
        for k, h in enumerate(PROFILE[key]):
            bx = bx0 + k * (bar_w + bar_gap)
            t += f"\\fill[{col}] ({bx:.2f},{base:.2f}) rectangle ({bx + bar_w:.2f},{base + h * bar_h:.2f});\n"
        t += f"\\draw[lane, {col}] ({x1 + 0.06:.2f},{y:.2f}) -- ({P4[0] + 0.55:.2f},{y:.2f});\n"
    t += (f"\\node[anchor=north, muted, text width={x1 - x0:.2f}cm, align=center] "
          f"at ({(x0 + x1) / 2:.2f},{Y_LLM - 0.50:.2f}) {{share of spans per category, \\\\ per condition and role}};\n")
    return t


def panel_distance() -> str:
    x0, x1 = P4
    t = "% ---- panel 4: distance to real\n" + header(4, x0, "Distance to HH real")
    ax = x0 + 0.85                     # vertical axis
    band_h = 0.34
    # the axis: HH real on top, distance grows downwards
    t += f"\\fill[cBand] ({ax - 0.16:.2f},{Y_REAL - band_h:.2f}) rectangle ({ax + 0.16:.2f},{Y_REAL:.2f});\n"
    t += f"\\draw[cMute, line width=0.7pt] ({ax:.2f},{Y_REAL:.2f}) -- ({ax:.2f},{Y_LLM - 0.45:.2f});\n"
    t += (f"\\draw[-{{Stealth[length=4pt,width=4pt]}}, cMute, line width=0.7pt] "
          f"({ax:.2f},{Y_LLM - 0.45:.2f}) -- ({ax:.2f},{Y_LLM - 0.75:.2f});\n")
    t += (f"\\node[anchor=north, muted, text width=1.4cm, align=center] at ({ax:.2f},{Y_LLM - 0.82:.2f}) "
          f"{{farther from real}};\n")
    # reference and the two measured points
    t += f"\\fill[cReal] ({ax:.2f},{Y_REAL:.2f}) circle (2.2pt);\n"
    t += f"\\fill[cRP] ({ax:.2f},{Y_RP:.2f}) circle (2.2pt);\n"
    t += f"\\fill[cLLM] ({ax:.2f},{Y_LLM:.2f}) circle (2.2pt);\n"
    lx = ax + 0.30
    t += (f"\\node[anchor=west, font=\\footnotesize\\bfseries, text=cReal, inner sep=0pt] at ({lx:.2f},{Y_REAL + 0.12:.2f}) "
          f"{{reference (HH real)}};\n")
    t += (f"\\node[anchor=north west, muted, text width=3.3cm] at ({lx:.2f},{Y_REAL - 0.04:.2f}) "
          f"{{grey: its own split-half band, the scale for every distance}};\n")
    t += (f"\\node[anchor=west, font=\\footnotesize, text=cRP, inner sep=0pt] at ({lx:.2f},{Y_RP:.2f}) "
          f"{{JSD(real, roleplay)}};\n")
    t += (f"\\node[anchor=west, font=\\footnotesize, text=cLLM, inner sep=0pt] at ({lx:.2f},{Y_LLM:.2f}) "
          f"{{JSD(real, LLM)}};\n")
    # the gap bracket
    bx = x1 - 0.75
    t += (f"\\draw[decorate, decoration={{brace, amplitude=4pt, mirror}}, cAcc, line width=0.8pt] "
          f"({bx:.2f},{Y_LLM:.2f}) -- ({bx:.2f},{Y_RP:.2f});\n")
    t += (f"\\node[anchor=west, font=\\small\\bfseries, text=cAcc, inner sep=0pt] at ({bx + 0.22:.2f},{(Y_RP + Y_LLM) / 2:.2f}) "
          f"{{{{\\unsansmath$\\Delta$}}}};\n")
    t += (f"\\node[anchor=north west, muted, text width={x1 - ax - 0.95:.2f}cm, align=left] at ({ax + 0.95:.2f},{Y_LLM - 0.30:.2f}) "
          f"{{{{\\unsansmath$\\Delta$}}: how much farther the LLM client is than a human role-play partner}};\n")
    return t


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-compile", action="store_true")
    args = ap.parse_args()

    tex = HEADER % dict(W=W, H=H)
    tex += panel_conditions() + panel_measurement() + panel_profiles() + panel_distance()
    tex += FOOTER
    OUT.write_text(tex, encoding="utf-8")
    print(f"wrote {OUT}")

    if not args.no_compile:
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode", OUT.name],
                           cwd=OUT.parent, capture_output=True, text=True)
        ok = r.returncode == 0 and (OUT.parent / "pipeline_figure.pdf").exists()
        print("compiled pipeline_figure.pdf" if ok else f"pdflatex FAILED:\n{r.stdout[-1500:]}")


if __name__ == "__main__":
    main()
