#!/usr/bin/env python3
"""Generate the noise-band / model-proximity figure as standalone TikZ.

Replaces the former Tables 4 and 5 of the main paper: every comparison's JSD to
HH real, placed on HH real's own split-half noise band, with the
size-matched null and the per-model bootstrap intervals on the same axis.

Sources
  results/tables/oncoco_noise_band.csv                     (unrounded bands, V)
  results/tables/oncoco_rq1b_model_realness_bootstrap.csv  (per-model 95% CIs)

Usage
  python3 analysis/semantic/oncoco/make_noise_band_tikz.py
  (writes + compiles results/figures/oncoco/tikz/noise_band_figure.tex)
"""
from __future__ import annotations

import csv
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TABLES = ROOT / "results" / "tables"
OUTDIR = ROOT / "results" / "figures" / "oncoco" / "tikz"
OUT = OUTDIR / "noise_band_figure.tex"

# --- rows: (display label, comparison key in noise-band csv, model key in CI csv, style)
ROWS = [
    ("HH roleplay", "HH_roleplay_chat", None, "rp"),
    ("H--LLM chat (pooled)", "H_LLM_roleplay_chat", None, "llm"),
    ("GPT-OSS-120B", "H_LLM_roleplay_chat [GPT_OSS_120B]", "GPT_OSS_120B", "model"),
    ("Llama 3.3 70B", "H_LLM_roleplay_chat [LLama3_3_70B]", "LLama3_3_70B", "model"),
    ("Mixtral 8x7B", "H_LLM_roleplay_chat [Mixtral]", "Mixtral", "model"),
]
PANELS = [("Client side", "Client"), ("Counselor side", "Counselor")]

# --- geometry (cm)
W_TOTAL, H_TOTAL = 17.40, 5.05
PW = 8.55                     # panel width
GAP = W_TOTAL - 2 * PW        # panel gap
XL, XR = 2.42, 6.92           # plot area inside a panel
XMAX = 0.60                   # axis maximum (JSD)
Y_ROWS = [3.62, 3.06, 2.30, 1.74, 1.18]
Y_TOP, Y_BOT = 3.92, 0.94     # band / plot extent
Y_AXIS = 0.94


def xpos(v: float) -> float:
    return XL + (XR - XL) * v / XMAX


def read_bands():
    out = {}
    with (TABLES / "oncoco_noise_band.csv").open() as fh:
        for r in csv.DictReader(fh):
            out[(r["comparison"], r["speaker"])] = r
    return out


def read_cis():
    out = {}
    with (TABLES / "oncoco_rq1b_model_realness_bootstrap.csv").open() as fh:
        for r in csv.DictReader(fh):
            out[(r["model"], r["speaker_type"])] = r
    return out


def main() -> None:
    bands, cis = read_bands(), read_cis()
    L: list[str] = []
    add = L.append

    add(r"% Auto-generated by analysis/semantic/oncoco/make_noise_band_tikz.py -- do not edit by hand.")
    add(r"\documentclass[border=1pt,10pt]{standalone}")
    add(r"\usepackage[T1]{fontenc}")
    add(r"\usepackage[scaled=0.92]{helvet}")
    add(r"\renewcommand{\familydefault}{\sfdefault}")
    add(r"\usepackage{sansmath}")
    add(r"\sansmath")
    add(r"\usepackage{tikz}")
    add(r"\usetikzlibrary{arrows.meta,positioning,calc}")
    add("")
    for name, hexv in [("cReal", "2C6E63"), ("cRP", "4A6E9B"), ("cLLM", "C0503C"),
                       ("cInk", "1F2328"), ("cMute", "70757D"), ("cRule", "CFD4DA"),
                       ("cPanel", "FBFBFC"), ("cBand", "E5E9EE")]:
        add(rf"\definecolor{{{name}}}{{HTML}}{{{hexv}}}")
    add("")
    add(r"\begin{document}")
    add(r"\begin{tikzpicture}[x=1cm,y=1cm]")
    add(rf"\path (0,0) rectangle ({W_TOTAL:.2f},{H_TOTAL:.2f});")

    for pi, (ptitle, speaker) in enumerate(PANELS):
        ox = pi * (PW + GAP)
        rows = [(lab, bands[(comp, speaker)], cis.get((mkey, speaker)), sty)
                for lab, comp, mkey, sty in ROWS]

        add("")
        add(rf"  % ---------------- {ptitle}")
        add(r"  \begin{scope}[shift={(%.2f,0)}]" % ox)
        add(r"  \draw[rounded corners=2.5pt, draw=cRule, fill=cPanel, line width=0.5pt]"
            rf" (0,0) rectangle ({PW:.2f},{H_TOTAL:.2f});")
        add(r"  \node[anchor=west, font=\small\bfseries, text=cInk, inner sep=0pt]"
            rf" at (0.24,{H_TOTAL - 0.42:.2f}) {{{ptitle}}};")
        add(r"  \node[anchor=east, font=\fontsize{5.6}{6.6}\selectfont, text=cMute, inner sep=0pt]"
            rf" at ({PW - 0.24:.2f},{H_TOTAL - 0.42:.2f}) {{distance to HH real (JSD), lower = closer}};")

        # noise band of the reference condition (identical to 3 decimals across rows)
        bm = sum(float(r[1]["band_mean"]) for r in rows) / len(rows)
        bp = sum(float(r[1]["band_p95"]) for r in rows) / len(rows)
        add(rf"  \fill[cBand] ({xpos(bm):.3f},{Y_BOT:.2f}) rectangle ({xpos(bp):.3f},{Y_TOP:.2f});")
        add(r"  \draw[cReal!55, line width=0.5pt, dash pattern=on 1.6pt off 1.4pt]"
            rf" ({xpos(bm):.3f},{Y_BOT:.2f}) -- ({xpos(bm):.3f},{Y_TOP:.2f});")
        add(r"  \node[anchor=south, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, align=center,"
            rf" inner sep=1pt] at ({xpos((bm + bp) / 2):.3f},{Y_TOP + 0.02:.2f})"
            r" {HH real's own\\split-half band};")

        # axis
        add(rf"  \draw[cRule, line width=0.4pt] ({XL:.2f},{Y_AXIS:.2f}) -- ({XR:.2f},{Y_AXIS:.2f});")
        t = 0.0
        while t <= XMAX + 1e-9:
            add(rf"  \draw[cRule, line width=0.4pt] ({xpos(t):.3f},{Y_AXIS:.2f}) --"
                rf" ({xpos(t):.3f},{Y_AXIS - 0.07:.2f});")
            add(r"  \node[anchor=north, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, inner sep=1.2pt]"
                rf" at ({xpos(t):.3f},{Y_AXIS - 0.07:.2f}) {{{t:.1f}}};")
            t += 0.2
        add(r"  \node[anchor=east, font=\fontsize{5.0}{5.8}\selectfont, text=cMute,"
            rf" inner sep=0pt] at ({PW - 0.24:.2f},{Y_ROWS[0] + 0.38:.2f}) {{Cram\'er's $V$}};")

        # group divider between the pooled rows and the per-model rows
        ymid = (Y_ROWS[1] + Y_ROWS[2]) / 2
        add(rf"  \draw[cRule, line width=0.4pt] (0.24,{ymid:.3f}) -- ({PW - 0.24:.2f},{ymid:.3f});")
        add(r"  \node[anchor=west, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, inner sep=0pt]"
            rf" at (0.24,{ymid - 0.17:.3f}) {{H--LLM by model}};")

        for (lab, b, ci, sty), y in zip(rows, Y_ROWS):
            col = {"rp": "cRP", "llm": "cLLM", "model": "cLLM"}[sty]
            jsd, nm, v = float(b["jsd_rp"]), float(b["nm_p95"]), float(b["cramers_v"])
            bold = r"\bfseries" if sty != "model" else ""
            indent = 0.44 if sty == "model" else 0.24
            add(r"  \node[anchor=west, font=\fontsize{6.4}{7.4}\selectfont" + bold +
                rf", text={'cInk' if sty != 'model' else 'cMute'}, inner sep=0pt]"
                rf" at ({indent:.2f},{y:.3f}) {{{lab}}};")
            add(r"  \node[anchor=west, font=\fontsize{4.7}{5.4}\selectfont, text=cMute, inner sep=0pt]"
                rf" at ({indent:.2f},{y - 0.21:.3f}) {{{b['n_comp_conv']} conversations\,\textbullet\,"
                rf"{float(b['ratio_to_floor']):.1f}$\times$ the floor}};")
            # size-matched null (P95)
            add(rf"  \draw[cMute!75, line width=0.6pt] ({xpos(nm):.3f},{y - 0.11:.3f}) --"
                rf" ({xpos(nm):.3f},{y + 0.11:.3f});")
            # bootstrap interval
            if ci:
                lo, hi = float(ci["jsd_ci_low"]), float(ci["jsd_ci_high"])
                add(rf"  \draw[{col}!55, line width=1.0pt] ({xpos(lo):.3f},{y:.3f}) --"
                    rf" ({xpos(hi):.3f},{y:.3f});")
                for e in (lo, hi):
                    add(rf"  \draw[{col}!55, line width=0.7pt] ({xpos(e):.3f},{y - 0.07:.3f}) --"
                        rf" ({xpos(e):.3f},{y + 0.07:.3f});")
            add(rf"  \fill[{col}] ({xpos(jsd):.3f},{y:.3f}) circle ({2.6 if sty != 'model' else 2.2:.1f}pt);")
            add(r"  \node[anchor=south, font=\fontsize{6.0}{7.0}\selectfont" + bold +
                rf", text={col}, inner sep=1.6pt] at ({xpos(jsd):.3f},{y + 0.06:.3f}) {{{jsd:.3f}}};")
            add(r"  \node[anchor=east, font=\fontsize{6.0}{7.0}\selectfont, text=cMute, inner sep=0pt]"
                rf" at ({PW - 0.24:.2f},{y:.3f}) {{{v:.2f}}};")
        add(r"  \end{scope}")

    # shared legend for the two auxiliary marks, drawn once under panel 1
    add("")
    add(r"  % ---------------- legend")
    lx, ly = 0.24, 0.36
    add(rf"  \draw[cMute!75, line width=0.6pt] ({lx:.2f},{ly - 0.09:.2f}) -- ({lx:.2f},{ly + 0.09:.2f});")
    add(r"  \node[anchor=west, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, inner sep=0pt]"
        rf" at ({lx + 0.10:.2f},{ly:.2f}) {{size-matched null P95: redrawn with replacement at these sizes}};")
    add(rf"  \fill[cBand] ({lx + 6.30:.2f},{ly - 0.09:.2f}) rectangle ({lx + 6.62:.2f},{ly + 0.09:.2f});")
    add(r"  \node[anchor=west, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, inner sep=0pt]"
        rf" at ({lx + 6.72:.2f},{ly:.2f}) {{noise band: HH real cut into two disjoint halves, 1{{,}}000 splits}};")
    add(r"  \node[anchor=west, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, inner sep=0pt]"
        rf" at ({lx + 13.30:.2f},{ly:.2f}) {{bars: 95\% bootstrap CI}};")

    add(r"\end{tikzpicture}")
    add(r"\end{document}")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    subprocess.run(["pdflatex", "-interaction=nonstopmode", OUT.name],
                   cwd=OUTDIR, check=True, stdout=subprocess.DEVNULL)
    print(f"compiled {OUT.with_suffix('.pdf')}")


if __name__ == "__main__":
    main()
