#!/usr/bin/env python3
"""Generate the HMM phase figure as standalone TikZ.

Three panels, one per chat condition, with identical node geometry so that only
the phase sizes and the transition weights differ. The point of the figure is
the third state: a low-occupancy residual phase in both human conditions and a
Help-led solution phase in H--LLM, entered about twice as readily.

Sources
  results/tables/oncoco_hmm_emissions_v2.csv     (occupancy + emission probs)
  results/tables/oncoco_hmm_transitions_v2.csv   (per-span transition matrix)
  results/tables/oncoco_hmm_model_selection.csv  (sequence and span counts, k=3)

Usage
  python3 analysis/semantic/oncoco/make_hmm_phase_tikz.py
  (writes + compiles results/figures/oncoco/tikz/hmm_phase_figure.tex)
"""
from __future__ import annotations

import csv
import subprocess
from tikz_fonts import scale_fonts
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
TABLES = ROOT / "results" / "tables"
OUTDIR = ROOT / "results" / "figures" / "oncoco" / "tikz"
OUT = OUTDIR / "hmm_phase_figure.tex"

CONDITIONS = [
    ("HH_roleplay_chat", "HH roleplay", "cRP"),
    ("HH_real_chat", "HH real", "cReal"),
    ("H_LLM_roleplay_chat", "H--LLM roleplay", "cLLM"),
]

# --- geometry (cm)
W_TOTAL, H_TOTAL = 13.05, 4.85
PW = 4.15
GAP = (W_TOTAL - 3 * PW) / 2
P_OPEN, P_CLAR, P_THIRD = (2.20, 3.32), (1.45, 1.92), (3.20, 1.92)
R0 = 0.88                      # radius at occupancy 1.0; area is proportional
BAR_X0, BAR_X1, BAR_Y, BAR_H = 0.22, 3.93, 0.70, 0.18
ARROW_PT_PER_PROB = 40.0       # linear, through the origin: width honors the ratio


def read_states():
    """occupancy and the three leading labels per (condition, state)."""
    occ, emis = {}, defaultdict(list)
    with (TABLES / "oncoco_hmm_emissions_v2.csv").open() as fh:
        for r in csv.DictReader(fh):
            key = (r["condition"], int(r["state"]))
            occ[key] = float(r["occupancy"])
            emis[key].append((float(r["prob"]), r["label"]))
    top = {k: sorted(v, reverse=True)[:3] for k, v in emis.items()}
    return occ, top


def read_trans():
    t = {}
    with (TABLES / "oncoco_hmm_transitions_v2.csv").open() as fh:
        for r in csv.DictReader(fh):
            t[(r["condition"], int(r["from_state"]), int(r["to_state"]))] = float(r["prob"])
    return t


def read_sizes():
    s = {}
    with (TABLES / "oncoco_hmm_model_selection.csv").open() as fh:
        for r in csv.DictReader(fh):
            if r["k"] == "3":
                s[r["condition"]] = (int(r["n_seqs"]), int(r["n_obs"]))
    return s


def roles(cond, occ, top):
    """Map the three fitted states onto Opening / Clarify / third.

    States are identified by their leading emission rather than by index, so a
    refit that reorders them cannot silently swap the panels around.
    """
    states = [s for (c, s) in occ if c == cond]
    lead = {s: top[(cond, s)][0][1] for s in states}
    opening = next(s for s in states if lead[s] == "Opening")
    clarify = max((s for s in states if s != opening), key=lambda s: occ[(cond, s)])
    third = next(s for s in states if s not in (opening, clarify))
    return opening, clarify, third


def fmt(p: float) -> str:
    return f"{p:.3f}"


def main() -> None:
    occ, top = read_states()
    trans, sizes = read_trans(), read_sizes()

    L: list[str] = []
    add = L.append
    add(r"% Auto-generated by analysis/semantic/oncoco/make_hmm_phase_tikz.py -- do not edit by hand.")
    add(r"\documentclass[border=1pt,10pt]{standalone}")
    add(r"\usepackage[T1]{fontenc}")
    add(r"\usepackage[scaled=0.92]{helvet}")
    add(r"\renewcommand{\familydefault}{\sfdefault}")
    add(r"\usepackage{sansmath}")
    add(r"\sansmath")
    add(r"\usepackage{tikz}")
    add(r"\usetikzlibrary{arrows.meta,positioning,calc}")
    add("")
    for name, hexv in [("cReal", "2C6E63"), ("cRP", "4A6E9B"), ("cLLM", "C0503C"),
                       ("cInk", "1F2328"), ("cMute", "70757D"), ("cRule", "CFD4DA"),
                       ("cPanel", "FBFBFC"), ("cBand", "E5E9EE")]:
        add(rf"\definecolor{{{name}}}{{HTML}}{{{hexv}}}")
    add("")
    add(r"\begin{document}")
    add(r"\begin{tikzpicture}[x=1cm,y=1cm,>={Stealth[round]}]")
    add(rf"\path (0,0) rectangle ({W_TOTAL:.2f},{H_TOTAL:.2f});")

    for ci, (key, title, col) in enumerate(CONDITIONS):
        ox = ci * (PW + GAP)
        o, c, t = roles(key, occ, top)
        occ_o, occ_c, occ_t = (occ[(key, s)] for s in (o, c, t))
        n_seq, n_obs = sizes[key]
        lead_label = top[(key, t)][0][1]
        # The node carries the same structural name in all three panels, so the panels stay
        # comparable. What the phase is made of differs, and that is said underneath: a
        # Help-led solution phase in H--LLM, a residual phase in both human conditions.
        third_name = "Phase 3"
        kind = "solution phase" if lead_label == "Help" else "residual phase"
        emph = lead_label == "Help"
        comp = ", ".join(f"{lab} ({p:.2f})" for p, lab in top[(key, t)][:2])

        add("")
        add(rf"  % ---------------- {title}")
        add(r"  \begin{scope}[shift={(%.2f,0)}]" % ox)
        add(r"  \draw[rounded corners=2.5pt, draw=cRule, fill=cPanel, line width=0.5pt]"
            rf" (0,0) rectangle ({PW:.2f},{H_TOTAL:.2f});")
        add(r"  \node[anchor=west, font=\small\bfseries, text=" + col + r", inner sep=0pt]"
            rf" at (0.22,{H_TOTAL - 0.38:.2f}) {{{title}}};")
        n_obs_tex = f"{n_obs:,}".replace(",", "{,}")
        add(r"  \node[anchor=west, font=\fontsize{5.0}{5.8}\selectfont, text=cMute, inner sep=0pt]"
            rf" at (0.22,{H_TOTAL - 0.62:.2f})"
            rf" {{{n_seq} conv.\,\textbullet\,{n_obs_tex} spans}};")

        rad = {s: R0 * (occ[(key, s)] ** 0.5) for s in (o, c, t)}

        # --- transitions (drawn under the nodes)
        def edge(a, b, prob, color, dash="", bend=""):
            (xa, ya), (xb, yb) = a, b
            dx, dy = xb - xa, yb - ya
            n = (dx * dx + dy * dy) ** 0.5
            ra, rb = 0.0, 0.0
            return xa, ya, xb, yb, dx / n, dy / n, ra, rb

        def arrow(p_from, r_from, p_to, r_to, prob, color, width, label_side):
            (xa, ya), (xb, yb) = p_from, p_to
            dx, dy = xb - xa, yb - ya
            n = (dx ** 2 + dy ** 2) ** 0.5
            ux, uy = dx / n, dy / n
            # 0.06 cm of air between the arrow and both circles
            sx, sy = xa + ux * (r_from + 0.06), ya + uy * (r_from + 0.06)
            ex, ey = xb - ux * (r_to + 0.10), yb - uy * (r_to + 0.10)
            add(rf"  \draw[->, {color}, line width={width:.2f}pt] ({sx:.3f},{sy:.3f}) --"
                rf" ({ex:.3f},{ey:.3f});")
            mx, my = (sx + ex) / 2, (sy + ey) / 2
            side = 1 if label_side == "above" else -1
            return mx - side * uy * 0.24, my + side * ux * 0.24

        # Opening -> Clarify: structural, drawn thin (not part of the comparison)
        p_oc = trans[(key, o, c)]
        mx, my = arrow(P_OPEN, rad[o], P_CLAR, rad[c], p_oc, "cMute!80", 0.55, "below")
        add(r"  \node[font=\fontsize{5.0}{5.8}\selectfont, text=cMute, fill=cPanel, inner sep=0.8pt]"
            rf" at ({mx:.3f},{my:.3f}) {{{fmt(p_oc)}}};")

        # Clarify <-> third state: the compared quantity, width proportional to the probability
        p_ct, p_tc = trans[(key, c, t)], trans[(key, t, c)]
        acol = col if emph else "cMute!85"
        lx, ly = arrow(P_CLAR, rad[c], P_THIRD, rad[t], p_ct, acol,
                       max(0.6, ARROW_PT_PER_PROB * p_ct), "above")
        add(r"  \node[font=\fontsize{6.6}{7.6}\selectfont\bfseries, text=" +
            (col if emph else "cInk") + r", fill=cPanel, inner sep=1.0pt]"
            rf" at ({lx:.3f},{ly + 0.20:.3f}) {{{fmt(p_ct)}}};")
        yb = P_CLAR[1] - 0.42
        dy = P_CLAR[1] - yb
        sx = P_CLAR[0] + max(0.0, rad[c] ** 2 - dy ** 2) ** 0.5 + 0.06
        ex = P_THIRD[0] - max(0.0, rad[t] ** 2 - dy ** 2) ** 0.5 - 0.10
        add(rf"  \draw[->, cMute!70, line width={max(0.6, ARROW_PT_PER_PROB * p_tc):.2f}pt]"
            rf" ({ex:.3f},{yb:.3f}) -- ({sx:.3f},{yb:.3f});")
        add(r"  \node[font=\fontsize{5.0}{5.8}\selectfont, text=cMute, fill=cPanel, inner sep=0.8pt]"
            rf" at ({(sx + ex) / 2:.3f},{yb - 0.15:.3f}) {{{fmt(p_tc)}}};")

        # --- nodes
        for (px, py), st, name in [(P_OPEN, o, "Opening"), (P_CLAR, c, "Clarify"),
                                   (P_THIRD, t, third_name)]:
            hot = emph and st == t
            add(rf"  \fill[{col}!{35 if hot else 16}] ({px:.2f},{py:.2f}) circle ({rad[st]:.3f});")
            add(rf"  \draw[{col}!{100 if hot else 55}, line width={1.0 if hot else 0.6:.1f}pt]"
                rf" ({px:.2f},{py:.2f}) circle ({rad[st]:.3f});")
            if st == o:
                # the Opening circle is too small for text at these occupancies (0.06--0.10),
                # so its label sits to the left in every panel, for consistency
                add(r"  \node[anchor=east, font=\fontsize{6.4}{7.4}\selectfont, inner sep=0pt]"
                    rf" at ({px - rad[st] - 0.12:.3f},{py:.2f})"
                    rf" {{\textcolor{{cInk}}{{\bfseries {name}}}~\textcolor{{cMute}}"
                    rf"{{{occ[(key, st)]:.2f}}}}};")
            else:
                add(r"  \node[font=\fontsize{6.4}{7.4}\selectfont\bfseries, text=" +
                    (col if hot else "cInk") + rf", inner sep=0pt] at ({px:.2f},{py + 0.11:.2f})"
                    rf" {{{name}}};")
                add(r"  \node[font=\fontsize{5.6}{6.6}\selectfont, text=cMute, inner sep=0pt]"
                    rf" at ({px:.2f},{py - 0.13:.2f}) {{{occ[(key, st)]:.2f}}};")

        # --- self-transitions, drawn on top of the nodes
        for (px, py), st, ang in [(P_OPEN, o, 90), (P_CLAR, c, 180), (P_THIRD, t, 90)]:
            import math
            r, rr = rad[st], 0.17
            ux, uy = math.cos(math.radians(ang)), math.sin(math.radians(ang))
            cx, cy = px + ux * (r + rr), py + uy * (r + rr)
            a0 = ang - 150
            add(rf"  \draw[->, cMute!65, line width=0.45pt]"
                rf" ({cx + rr * math.cos(math.radians(a0)):.3f},"
                rf"{cy + rr * math.sin(math.radians(a0)):.3f})"
                rf" arc[start angle={a0}, delta angle=300, radius={rr:.2f}];")
            if st != t:
                continue          # Opening and Clarify keep the loop, not the number
            add(r"  \node[font=\fontsize{4.8}{5.6}\selectfont, text=cMute, inner sep=1.0pt,"
                rf" anchor=south] at ({px + ux * (r + 2 * rr + 0.04):.3f},"
                rf"{py + uy * (r + 2 * rr + 0.04):.3f}) {{{fmt(trans[(key, st, st)])}}};")

        # --- occupancy strip: the same 0-1 scale in all three panels
        x = BAR_X0
        for s, shade in [(o, 30), (c, 55), (t, 100 if emph else 70)]:
            w = (BAR_X1 - BAR_X0) * occ[(key, s)]
            add(rf"  \fill[{col}!{shade}] ({x:.3f},{BAR_Y:.2f}) rectangle"
                rf" ({x + w - 0.03:.3f},{BAR_Y + BAR_H:.2f});")
            x += w
        add(r"  \node[anchor=east, font=\fontsize{4.8}{5.6}\selectfont, text=cMute, inner sep=0pt]"
            rf" at ({BAR_X1:.2f},{BAR_Y + BAR_H + 0.15:.2f}) {{occupancy}};")
        add(r"  \node[anchor=west, font=\fontsize{4.8}{5.6}\selectfont, text=cMute, inner sep=0pt]"
            rf" at ({BAR_X0:.2f},{BAR_Y + BAR_H + 0.15:.2f}) {{Opening\,\textbar\,Clarify\,\textbar\,"
            rf"{third_name}}};")
        add(r"  \node[anchor=west, font=\fontsize{4.8}{5.6}\selectfont, text=cMute, inner sep=0pt,"
            rf" align=left, text width={PW - 0.44:.2f}cm] at (0.22,{BAR_Y - 0.30:.2f})"
            rf" {{Phase 3 is a {kind}, led by {comp}}};")
        add(r"  \end{scope}")

    add(r"\end{tikzpicture}")
    add(r"\end{document}")

    OUT.write_text(scale_fonts("\n".join(L)) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    subprocess.run(["pdflatex", "-interaction=nonstopmode", OUT.name],
                   cwd=OUTDIR, check=True, stdout=subprocess.DEVNULL)
    print(f"compiled {OUT.with_suffix('.pdf')}")


if __name__ == "__main__":
    main()
