#!/usr/bin/env python3
"""Held-out prompt replay: do the dosed prompts transfer to conversations they were not tuned on?

Prompts D and G were written and dosed on the 90 GPT-OSS-120B conversations. Here they are
applied unchanged to the 117 Llama 3.3 70B conversations that ran under the same plain-text
template family (exports E04 and E09), 114 of them with personas that never occur
in the GPT-OSS deployment. The generator is GPT-OSS-120B in every generated arm, so arm A
(the logged Llama prompt replayed) is the baseline that isolates the prompt:

  O_llama  original Llama client text through the current pipeline
  A_llama  logged prompt, regenerated by GPT-OSS-120B
  D_llama  prompt D unchanged
  G_llama  prompt G unchanged (phase decoded on the original Llama history)

Reported per group, as in Table 4 of the paper: JSD to HH real with a conversation bootstrap
interval, the proximity gap against HH roleplay, the JSD to HH roleplay (profile check), the
signature metrics, and the client-led entry rate into the help phase of the HH-real HMM.

Outputs results/tables/oncoco_prompt_replay_heldout.{csv,tex}.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(ROOT / "analysis/prompt_replay"))

from oncoco_noise_band_analysis import count_matrix, js_distance, load_rows, span_labels_by_conversation  # noqa: E402
from oncoco_prompt_replay import bootstrap, client_rows, signature_metrics  # noqa: E402

NORM = ROOT / "data/processed/combined/normalized/oncoco_classification_all.json"
HELD = ROOT / "data/processed/prompt_replay_heldout"
TABLES = ROOT / "results/tables"
REF, RP, LLM, MODEL = "HH_real_chat", "HH_roleplay_chat", "H_LLM_roleplay_chat", "LLama3_3_70B"
PLAIN_FILES = {"data/raw/human_llm/chats/LLama3_3_70B/E04.json",
               "data/raw/human_llm/chats/LLama3_3_70B/E09.json"}
SUFFIX = "_llama"
NAMES = {"orig": "Llama 3.3 70B deployment (plain template)", "O": "O: original text, re-classified",
         "A": "A: logged prompt, GPT-OSS", "D": "D: dosed rules, unchanged", "G": "G: phase-dependent rules, unchanged"}


def drop_ungenerated(rows: list[dict], status_paths: list[Path]) -> list[dict]:
    bad = set()
    for sp in status_paths:
        if sp.exists():
            for r in csv.DictReader(sp.open(encoding="utf-8")):
                if r["status"] != "generated":
                    bad.add((f"H_LLM_replay_{r['arm']}{SUFFIX}_chat", str(r["conv_id"]), int(r["message_number"])))
    kept = [r for r in rows if not (r.get("speaker_type") == "Client" and
                                    (r.get("source"), str(r.get("id")), int(r.get("msg_message_number") or 0)) in bad)]
    print(f"dropped {len(rows) - len(kept)} ungenerated client messages")
    return kept


def entry_rate(dec, rows: list[dict], source: str, history: dict | None) -> tuple[float, int]:
    """Share of clarification-phase client turns after which the HH-real HMM is in the help phase."""
    conv = defaultdict(dict)
    for r in rows:
        if r.get("source") != source:
            continue
        sents = sorted(r.get("sentence_classification") or [], key=lambda s: s.get("sentence_index", 0))
        conv[f"{r.get('source_file', '')}::{r.get('id')}"][int(r.get("msg_message_number") or 0)] = (
            r.get("speaker_type"), [s["predicted_label"] for s in sents if s.get("predicted_label")])
    moves, n = Counter(), 0
    for key, msgs in conv.items():
        hist = (history or conv).get(key, msgs)
        for num in sorted(msgs):
            spk, labs = msgs[num]
            if spk != "Client" or not labs:
                continue
            prefix = [dec.idx[dec.SEQ.role_category(l)[1]] for m in sorted(hist) if m < num for l in hist[m][1]]
            before = dec.decode(prefix)[-1] if prefix else 2
            if before != 0:
                continue
            after = dec.decode(prefix + [dec.idx[dec.SEQ.role_category(l)[1]] for l in labs])[-1]
            n += 1
            moves[after] += 1
    return (moves[1] / n if n else float("nan")), n


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--arms", default="O,A,D,G")
    ap.add_argument("--n-boot", type=int, default=20000)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()
    arms = [a for a in args.arms.split(",") if (HELD / f"oncoco_classification_{a}.json").exists()]
    master = load_rows(NORM)
    replay = []
    for a in arms:
        replay += load_rows(HELD / f"oncoco_classification_{a}.json")
    replay = drop_ungenerated(replay, [HELD / f"replay_chat_{a}_turn_status.csv" for a in arms])
    # the held-out deployment rows get their own source name so they do not mix with other Llama courses
    orig_rows = [dict(r, source="orig") for r in master
                 if r.get("source") == LLM and r.get("model") == MODEL and r.get("source_file") in PLAIN_FILES]
    rows = [r for r in master if r.get("source") in (REF, RP)] + orig_rows + replay

    groups = [(REF, "HH real"), (RP, "HH roleplay"), ("orig", NAMES["orig"])] + \
             [(f"H_LLM_replay_{a}{SUFFIX}_chat", NAMES[a]) for a in arms]
    labels_by_group = {g: span_labels_by_conversation(rows, g, "Client") for g, _ in groups}
    all_labels = sorted({l for d in labels_by_group.values() for labs in d.values() for l in labs})
    idx = {l: i for i, l in enumerate(all_labels)}
    mats = {g: count_matrix(labels_by_group[g], idx)[1] for g in labels_by_group}

    from phase_decoder import PhaseDecoder
    dec = PhaseDecoder(NORM)
    hist_rows = [dict(r, source="orig") for r in orig_rows]

    def history_of(source_rows):
        conv = defaultdict(dict)
        for r in source_rows:
            sents = sorted(r.get("sentence_classification") or [], key=lambda s: s.get("sentence_index", 0))
            conv[f"{r.get('source_file', '')}::{r.get('id')}"][int(r.get("msg_message_number") or 0)] = (
                r.get("speaker_type"), [s["predicted_label"] for s in sents if s.get("predicted_label")])
        return conv
    orig_hist = history_of(hist_rows)

    records = []
    for g, name in groups:
        rec = dict(group=g, name=name, n_conv=mats[g].shape[0], n_spans=int(mats[g].sum()))
        if g != REF:
            rec.update(bootstrap(mats, g, args.n_boot, args.seed))
        if g not in (REF, RP):
            rec["jsd_roleplay"] = js_distance(mats[RP].sum(axis=0), mats[g].sum(axis=0))
        rec.update(signature_metrics(client_rows(rows, g)))
        rate, n = entry_rate(dec, rows, g, orig_hist if g.startswith("H_LLM_replay_") else None)
        rec["entry_rate"], rec["entry_turns"] = rate, n
        records.append(rec)
        print({k: (round(v, 3) if isinstance(v, float) else v) for k, v in rec.items()
               if k in ("name", "n_conv", "jsd_real", "jsd_real_lo", "jsd_real_hi", "delta", "delta_lo", "delta_hi",
                        "jsd_roleplay", "problem_d1", "solution_pooled", "share_conv_rejection",
                        "share_conv_request", "neg_pos_ratio", "median_words", "entry_rate")})
    df = pd.DataFrame(records)
    out = TABLES / "oncoco_prompt_replay_heldout"
    df.to_csv(out.with_suffix(".csv"), index=False)

    def f3(v):
        return "" if pd.isna(v) else f"{v:.3f}"

    def ci(r, k, sign=False):
        if pd.isna(r.get(k)):
            return ""
        fmt = "+.3f" if sign else ".3f"
        return f"{r[k]:{fmt}} [{r[k + '_lo']:{fmt}}, {r[k + '_hi']:{fmt}}]".replace("-", "$-$")

    lines = [r"\begin{tabular}{lrrrrrrrrr}", r"\toprule",
             r"Group & JSD to HH real [95\% CI] & $\Delta$ [95\% CI] & JSD to roleplay & Problem d1 & Solution & Rej.\ conv. & Neg:Pos & Words & Entry \\",
             r"\midrule"]
    for _, r in df.iterrows():
        lines.append(" & ".join([
            r["name"], ci(r, "jsd_real"), ci(r, "delta", True), f3(r.get("jsd_roleplay")),
            f3(r.get("problem_d1")), f3(r.get("solution_pooled")),
            f"{100 * r['share_conv_rejection']:.0f}\\%", f"{r['neg_pos_ratio']:.2f}", f"{r['median_words']:.0f}",
            f"{100 * r['entry_rate']:.1f}\\%"]) + r" \\")
        if r["group"] in (RP, "orig"):
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}"]
    out.with_suffix(".tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", out.with_suffix(".csv"), out.with_suffix(".tex"))


if __name__ == "__main__":
    main()
